### ISSUE TITLE
getParts function will crash if string param is special chars but not match splitOnSpecialChars

### ISSUE THREAD

**Issue by hirohe** [mesqueeb/case-anything#7]
example

```js
const caseAnything = require('case-anything')

cascaseAnything.camelCase('你好')
cascaseAnything.kebabCase('こんにちは')
```

this code will throw error

```bash
/sandbox/node_modules/case-anything/dist/index.cjs.js:29
    return noSpecialChars ? parts.map(function (part) { return part.normalize('NFD').replace(/[^a-zA-ZØßø0-9]/g, ''); }) : parts;
                                  ^

TypeError: Cannot read property 'map' of null
    at getParts (/sandbox/node_modules/case-anything/dist/index.cjs.js:29:35)
    at Object.camelCase (/sandbox/node_modules/case-anything/dist/index.cjs.js:51:12)
    at Server.<anonymous> (/sandbox/src/index.js:7:28)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:695:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
```

**Comment by mesqueeb** [comment]
@hirohe because of the nature of the how case-anything was implemented it only supports regular alphabet with the most common Latin-1 Supplement special characters.

See the source code here: https://github.com/mesqueeb/case-anything/blob/production/src/utils.ts#L14

I'm not sure how to support other languages. I think it might not be possible without making the library much bigger.

However, it's best if the library doesn't throw an error of course, so if you have any implementation ideas how to make sure the library doesn't throw an error, please let me know!

: )

**Comment by hirohe** [comment]
Hi, @mesqueeb thanks for reply

this issue's example is used old version. sorry that i didn't write it down

for current version `2.1.2`, I tested this non-ascii strings, it will not throw error, although non-ascii only will return empty string.

```js
caseAnything.camelCase('你好') \\ output: 
caseAnything.camelCase('abc你好') \\ output: abc
```

so is it fixed ?

**Comment by mesqueeb** [comment]
@hirohe try this:
```js
camelCase('abcこんにちは', { keepSpecialCharacters: true })
```

**Comment by hirohe** [comment]
```js
camelCase('abcこんにちは', { keepSpecialCharacters: true }) // output: abc
camelCase('こんにちはabc', { keepSpecialCharacters: true }) // output: こんにちはabc
camelCase('こんにaちはbcおわり', { keepSpecialCharacters: true }) // output: こんにaちはbc
```

so current behavior is only "last part" of special characters will be removed, if keepSpecialCharacters is true.

**Comment by mesqueeb** [comment]
@hirohe i will fix shortly

**Comment by mesqueeb** [comment]
@hirohe fixed in latest version!! : )

<sub>--<br />case-anything was made with 💜 by Luca Ban.<br />You cannot sponsor every project, but next time you do, think of <a href="https://github.com/sponsors/mesqueeb">this one</a> for its prolonged maintenance.</sub>
