### ISSUE TITLE
Erroneous handling of strng 'MSkS'

### ISSUE THREAD

**Issue by st-clair-clarke** [mesqueeb/case-anything#8]
Hi, 
I like 'case-anything'. However, I met an edge case today that you should examine.

The following two conversion differ

```
lowerCase('MSkS') // 'm sk s'
'MSkS'.toLowerCase() // 'msks'
```

So far, it is the only time I have seen where lowerCase() fails, and I have been using it extensively. I hope you can find out the issue - it did cost be the better part of a day to track the erroneous conversion.

**Comment by mesqueeb** [comment]
@st-clair-clarke this is not an issue, it's by design.

case-anything will convert casing **and add spaces** for these case change functions:
- lowerCase
- upperCase
- capitalCase

The reason is, if you don't want spaces to be added, then you can just use the native `.toLowerCase()` and `.toUpperCase()`.

Your specific use case: `MSkS` is being detected as the parts `['M', 'Sk', 'S']` that is because all functions of case-anything will try and detect and take apart
1. capitalised words
2. upper case words
3. lower case words

in this case it
1. found the capitalised word `Sk`
2. found the remaining upper case words `M` and `S`

Please let me know if there is anything you have a different view on, because I'm really interested in understanding all use cases.

Let's keep the discussion going!

**Comment by mesqueeb** [comment]
@st-clair-clarke 

BTW,
For part detection I use this regex under the hood: `/^[a-zà-öø-ÿ]+|[A-ZÀ-ÖØ-ß][a-zà-öø-ÿ]+|[a-zà-öø-ÿ]+|[0-9]+|[A-ZÀ-ÖØ-ß]+(?![a-zà-öø-ÿ])/g`

See how the part are detected in the order I explained:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/3253920/147676323-374f077e-dee2-4d3e-84ad-37c4038b22f2.png">

[regexr.com/6cefm](https://regexr.com/6cefm)
please play around with the regex yourself to see if there are any other use cases you have that are solved by tweaking the regex, and if you do find something you think is useful, please let me know how to tweak the regex and why! : )
